# This workflow's intent is to send 'make check' and 'API test' success statuses
# to Pull Requests in ceph.git that do not require actually running those checks.
# This workflow should only be triggered by other workflows.

name: PR Status Check Faker

on:
  workflow_call:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true
        type: string
      pr_sha:
        description: "Pull Request SHA"
        required: true
        type: string
      triggered_by:
        description: "URL of workflow that triggered the Check Faker"
        required: true
        type: string

jobs:
  send-status-checks:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: read

    steps:
      - name: Get commit SHA for PR
        id: pr
        uses: octokit/request-action@dad4362715b7fb2ddedf9772c8670824af564f0d
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ inputs.pr_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract commit SHA
        id: extract
        env:
          PR_SHA: ${{ steps.pr.outputs.data }}
        run: |
          sha=$(echo "$PR_SHA" | jq -r .head.sha)
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Send "make check" success status
        env:
          SHA: ${{ steps.extract.outputs.sha }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/statuses/$SHA \
            -d '{
              "state": "success",
              "context": "make check",
              "description": "Actual test run not required",
              "target_url": "${{ inputs.triggered_by }}"
            }'

      - name: Send "ceph API tests" success status
        env:
          SHA: ${{ steps.extract.outputs.sha }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/statuses/$SHA \
            -d '{
              "state": "success",
              "context": "ceph API tests",
              "description": "Actual test run not required",
              "target_url": "${{ inputs.triggered_by }}"
            }'

      - name: Send "ceph windows tests" success status
        env:
          SHA: ${{ steps.extract.outputs.sha }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/statuses/$SHA \
            -d '{
              "state": "success",
              "context": "ceph windows tests",
              "description": "Actual test run not required",
              "target_url": "${{ inputs.triggered_by }}"
            }'

      - name: Send "make check (arm64)" success status
        env:
          SHA: ${{ steps.extract.outputs.sha }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/statuses/$SHA \
            -d '{
              "state": "success",
              "context": "make check (arm64)",
              "description": "Actual test run not required",
              "target_url": "${{ inputs.triggered_by }}"
            }'
